# Generated by Django 5.1.15 on 2026-05-14 15:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
        ('pigeons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('numero', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nom', models.CharField(blank=True, default='', max_length=100)),
                ('superficie', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('description', models.TextField(blank=True, default='')),
                ('statut_occupation', models.CharField(choices=[('LIBRE', 'Libre'), ('OCCUPE_PIGEON', 'Occupée par un pigeon'), ('OCCUPE_COUPLE', 'Occupée par un couple')], db_index=True, default='LIBRE', max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cage',
                'verbose_name_plural': 'Cages',
                'ordering': ('numero',),
            },
        ),
        migrations.CreateModel(
            name='CageOccupation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('date_affectation', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_liberation', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='occupations', to='cages.cage')),
                ('couple', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='couples.couple')),
                ('pigeon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupations', to='pigeons.pigeon')),
            ],
            options={
                'verbose_name': 'Occupation de cage',
                'verbose_name_plural': 'Occupations de cage',
                'ordering': ('-date_affectation',),
            },
        ),
        migrations.AddIndex(
            model_name='cage',
            index=models.Index(fields=['user', 'statut_occupation'], name='idx_cage_user_statut'),
        ),
        migrations.AddConstraint(
            model_name='cageoccupation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('couple__isnull', True), ('pigeon__isnull', False)), models.Q(('couple__isnull', False), ('pigeon__isnull', True)), _connector='OR'), name='chk_occupation_pigeon_xor_couple'),
        ),
        migrations.AddConstraint(
            model_name='cageoccupation',
            constraint=models.UniqueConstraint(condition=models.Q(('date_liberation__isnull', True)), fields=('cage',), name='unique_occupation_active_per_cage'),
        ),
        migrations.AddConstraint(
            model_name='cageoccupation',
            constraint=models.UniqueConstraint(condition=models.Q(('date_liberation__isnull', True), ('pigeon__isnull', False)), fields=('pigeon',), name='unique_occupation_active_per_pigeon'),
        ),
        migrations.AddConstraint(
            model_name='cageoccupation',
            constraint=models.UniqueConstraint(condition=models.Q(('couple__isnull', False), ('date_liberation__isnull', True)), fields=('couple',), name='unique_occupation_active_per_couple'),
        ),
    ]
