# Generated by Django 5.1.15 on 2026-05-14 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pigeons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Couple',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('date_formation', models.DateField()),
                ('date_dissolution', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('DISSOUS', 'Dissous')], db_index=True, default='ACTIF', max_length=10)),
                ('femelle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couples_femelle', to='pigeons.pigeon')),
                ('male', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='couples_male', to='pigeons.pigeon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='couples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Couple',
                'verbose_name_plural': 'Couples',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'statut'], name='idx_couple_user_statut')],
                'constraints': [models.CheckConstraint(condition=models.Q(('male', models.F('femelle')), _negated=True), name='chk_couple_different_pigeons'), models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('male',), name='unique_male_per_couple_actif'), models.UniqueConstraint(condition=models.Q(('statut', 'ACTIF')), fields=('femelle',), name='unique_femelle_per_couple_actif')],
            },
        ),
    ]
