# Generated by Django 5.1.15 on 2026-05-14 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couples', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('date_ponte', models.DateField()),
                ('date_eclosion', models.DateField(blank=True, null=True)),
                ('nb_pigeonneaux', models.PositiveSmallIntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('couple', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reproductions', to='couples.couple')),
            ],
            options={
                'verbose_name': 'Reproduction',
                'verbose_name_plural': 'Reproductions',
                'ordering': ('-date_ponte', '-created_at'),
                'indexes': [models.Index(fields=['couple'], name='idx_repro_couple')],
                'constraints': [models.CheckConstraint(condition=models.Q(('nb_pigeonneaux__gte', 0)), name='chk_repro_nb_positif'), models.CheckConstraint(condition=models.Q(('date_eclosion__isnull', True), ('date_eclosion__gte', models.F('date_ponte')), _connector='OR'), name='chk_repro_eclosion_date')],
            },
        ),
    ]
