# Generated by Django 5.1.15 on 2026-05-14 15:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pigeon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, editable=False, null=True)),
                ('bague', models.CharField(db_index=True, max_length=50, unique=True)),
                ('sexe', models.CharField(choices=[('MALE', 'Mâle'), ('FEMALE', 'Femelle')], max_length=10)),
                ('race', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('couleur', models.CharField(blank=True, default='', max_length=100)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo_url', models.TextField(blank=True, default='')),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('VENDU', 'Vendu'), ('MORT', 'Mort'), ('PERDU', 'Perdu')], db_index=True, default='ACTIF', max_length=10)),
                ('mere', models.ForeignKey(blank=True, limit_choices_to={'sexe': 'FEMALE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_par_mere', to='pigeons.pigeon')),
                ('pere', models.ForeignKey(blank=True, limit_choices_to={'sexe': 'MALE'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enfants_par_pere', to='pigeons.pigeon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pigeons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pigeon',
                'verbose_name_plural': 'Pigeons',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['user', 'statut'], name='idx_pigeon_user_statut'), models.Index(fields=['pere'], name='idx_pigeon_pere'), models.Index(fields=['mere'], name='idx_pigeon_mere')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('pere', models.F('id')), _negated=True), models.Q(('mere', models.F('id')), _negated=True)), name='chk_pigeon_not_own_parent')],
            },
        ),
    ]
