# Generated by Django 5.1.15 on 2026-05-14 15:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pigeons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sortie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifiant')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('type_sortie', models.CharField(choices=[('VENTE', 'Vente'), ('DECES', 'Décès'), ('PERTE', 'Perte')], max_length=10)),
                ('date_sortie', models.DateField()),
                ('prix', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('acheteur', models.CharField(blank=True, default='', max_length=200)),
                ('cause', models.TextField(blank=True, default='')),
                ('circonstance', models.TextField(blank=True, default='')),
                ('pigeon', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sortie', to='pigeons.pigeon')),
            ],
            options={
                'verbose_name': 'Sortie',
                'verbose_name_plural': 'Sorties',
                'ordering': ('-date_sortie', '-created_at'),
                'indexes': [models.Index(fields=['type_sortie', '-date_sortie'], name='idx_sortie_type_date')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('type_sortie', 'VENTE'), _negated=True), models.Q(('prix__isnull', False), models.Q(('acheteur', ''), _negated=True)), _connector='OR'), name='chk_sortie_vente_complete')],
            },
        ),
    ]
